### ISSUE TITLE
[DOCS] Need Quickstart/Install Documentation

### ISSUE THREAD

**Issue by nicholasmhughes** [salt-extensions/saltext-prometheus#1]
**Description**
We need to show users how to install this extension. Use cases and example configurations are also helpful.

**Suggested Fix**
The salt-ext-modules-vmware repo might have some ideas on how to structure that documentation.

**Comment by waynew** [comment]
FWIW part of @barbaricyawps work on Salt Docs will be creating some good docs templates and guidelines, specifically targeted towards modules

**Comment by barbaricyawps** [comment]
@waynew is correct. My current project is to create module documentation standards that include a set of content and organization guidelines + a template + an example of good documentation to model. Once those are ready, we'll open them up the community for review, comment, and validation. @nicholasmhughes , it would be awesome to get your feedback on these deliverables when they're ready.

**Comment by Artanicus** [comment]
Would it be possible to have a single simple example in the README in the meanwhile before better documentation is made via the new templates? Don't let perfect be the enemy of having at least something, as right now there's literally nothing but boilerplate.
